ip: "127.0.0.1"
port: 5500
api:
usecase:
db:
  users:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "catjkm8800"
    dbname: "users"

  articles:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "catjkm8800"
    dbname: "articles"
